blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability Report
    url: https://github.com/byrdltd/whyDPI/security/advisories/new
    about: Please report security vulnerabilities privately via GitHub Security Advisories
  - name: General Questions
    url: https://github.com/byrdltd/whyDPI/issues/new?labels=question
    about: Ask questions about using whyDPI or network security concepts
